In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
vect= CountVectorizer(binary=True)
#corpus with three documents
corpus = ["NLP is awesome","I want to start an NLP Company","Top unicorns are NLP Techniques"]

In [4]:
vect.fit(corpus)

CountVectorizer(binary=True)

In [5]:
#List of unique terms present in the corpus
vocab =vect.vocabulary_

In [6]:
vocab

{'nlp': 5,
 'is': 4,
 'awesome': 2,
 'want': 11,
 'to': 8,
 'start': 6,
 'an': 0,
 'company': 3,
 'top': 9,
 'unicorns': 10,
 'are': 1,
 'techniques': 7}

In [7]:
vect.transform(["NLP is awesome","I want to start an NLP company","Top unicorns use NLP techniques"]).toarray()

array([[0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0]])

In [10]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

def cosine_similarity_text(texts):
    """
    Calculates the cosine similarity between all pairs of texts in a list.
    """
    # create TfidfVectorizer object
    vectorizer = TfidfVectorizer()

    # create sparse matrix of text vectors
    text_vectors = vectorizer.fit_transform(texts)

    # convert sparse matrix to dense matrix
    dense_vectors = text_vectors.todense()

    # calculate cosine similarity
    cos_sim = np.dot(dense_vectors, dense_vectors.T)

    return cos_sim

In [11]:
cos_sim = cosine_similarity_text(corpus)

print(cos_sim)

[[1.         0.09841374 0.10914377]
 [0.09841374 1.         0.07232613]
 [0.10914377 0.07232613 1.        ]]


In [8]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity((vect.transform(["ML is an elective subject"]).toarray()),vect.transform(["Airbnb is an NLP company"]).toarray())

In [9]:
similarity

array([[0.70710678]])